# Generated by Django 4.1.4 on 2022-12-12 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('data', models.CharField(default='', max_length=8496)),
            ],
        ),
        migrations.CreateModel(
            name='TargetCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MID', 'Mobile ID'), ('GEO', 'Geo-Polygon'), ('IP', 'IP Address')], default='MID', max_length=256)),
                ('value', models.CharField(default='', max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='URLParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsp', models.CharField(max_length=256)),
                ('mid', models.CharField(max_length=256)),
                ('ip', models.CharField(max_length=256)),
                ('geo', models.CharField(max_length=256)),
            ],
        ),
    ]
